---
title: Квантитативная грамматика русских предложных конструкций
subtitle: Проект РФФИ 17-29-09159 офи_м

description: >-
  Информационный сайт проекта РФФИ 17-29-09159 офи_м
  «Квантитативная грамматика русских предложных конструкций»,
  разработанного на кафедре математической лингвистики СПбГУ.
copyright: 2019–2020 &copy; Кафедра математической лингвистики СПбГУ

header_pages:
  - index.md
  - staff.md
  - papers.md
  - data.md

defaults:
  - scope:
      path: "assets/data/2018"
    values:
      year: 2018
  - scope:
      path: "assets/data/2019"
    values:
      year: 2019

theme: minima

plugins:
  - jekyll-tabs
